package:
  name: lindelint
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - setuptools
  - numpy
  run:
  - python
  - setuptools
  - numpy
  - matplotlib
  - tqdm
  - scikit-learn
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'Linear Delaunay Interpolator

    '
  dev_url: https://github.com/uibcdf/LinDelInt
  doc_url: https://uibcdf.org/LinDelInt
